language: node_js
node_js:
- 9.8.0
# Caching phrase.
cache:
 directories:
  - node_modules

# Dependency installation phrase.
install:
- npm install

# Build phrase
script:
- ng build

# Deployment phrase
deploy:
  provider: firebase
  token:
    secure: "AnrItUk83BXmkr0qY8J+k2ecQ+DHMZz0jXwkqWMUpkwK7Q01FnJtPWujQgdkMwkx6LyRL/HoCpn7QVtrPOVqcjaD4zib1TGUme2YJ99jPl512IrIO7x0SAjjcR3H3ywPTEGXXSQz/jzArt+svHuWZ4B8GR62PrKZUfToNUJjl4bKZjgiCd2zgDhx09Jfa78NbLm+OFTDehCD4X08q4odh6FV2V6EsTDp5R1iXrfWBRnRhk0G19/bTVSy759lylOms8d2ZeBTMYLVwzgAoqNATSPmkr6bErxYaxdXlKnd/893k636mfJRkwIrWaO/uD2eg0vD3Vj3+5zzhaWLftFc8bgkVPHoYhEDx4fKrMl7kY2C6UMZKp2t+CiD0tdOwR0SM997oLROxMyc1qXp433fj7CwvTeG7PN4+Yj+x+rP+sqyCYW/t7GXNiJEk4QURgT+EynwcfeyCpNhsckTOucOmZbhcDTbqWgkl5pdm5SEXGHf6nQmWCe0SSWsTUKWUXG4rrjDPCoYUIKc67UudPk9akCUEPE30uA2YnsO4lWmvCegBycMPcyZjuJj608e8op1lxDrZaoMR/R18Y5fg8i3J6nURPd8yRJSizHybfxmBuDgv1EziotXv1MV2HHQRn1jAGQ4T2CNSWApeIeEPSQKlomI8BmPcpyAR2vA2yR9qtg="
  project: "ngx-resume"
  on: 
   branch: "angular.5-migration"