language: node_js
node_js:
- 9.8.0
# Caching phrase.
cache:
 directories:
  - node_modules

# Dependency installation phrase.
install:
- npm install

# Build phrase
script:
- ng build

# Deployment phrase
deploy:
  provider: firebase
  token:
    secure: "BgH+Zxn7Q8nrYSdjAsnogywrRe31KZTSVDF4J28O2TrngZI7KGjnwKrO2yChQ8OyV17r+WIlYO/zaDl4dyfJztViTr3al+IjJ5z2kSOO4zWluZ8P3gh/lf0kCGa1JFI+oWSs8/jDbxv5AVFzHzKKUP280CW/tGoGOuTX8th6ZmtAQUNZEVYdjqYksP6bddBGWrt4vXbF24Mru2MbELrFL/Awkri1wuDUl+NK1neE1BzRCwgVDQmVrc9RWtqZIUNGgMCyLkPqgXBoNUFaynHqxGwo8RTSJjK9gmm98UuHBWEk6W4eLo+WGiFucEEE9jpKQ8ZXfAWU7fAmGM1QjDa/Xu8GEFxI1hurE+mPDHCwDzfSvRGydC2E4vk6v4qdMMGWL7bP/Y8ZdXOXcAO/oyRp8glJ6XTkkCOgGb9RdkUdfVziV6zJ52qthk5c1WlMbYQREkvifDhbmAn1ErGt7cd6NCEfKtp9+84mRv0+WclvRNIvxY7FDYV7ahuZxar9cZwipo5TaL2dZFqQgXLRzMyCg39UfQjRoiIWO+3L6V3TfJWlcwEmhwU3F1HxkfP5dpRXQimoB5nvOkzqp609zEr5gxak02DHc6/xihBQYQfBQifno7SIYbHhvJNJgTyyi/7oizLbYo5yKyWS/Sr/BUqqskGEa87dTDodncykpmOpR08="
  project: "ngx-resume"
  on: 
   branch: "angular.5-migration"